### ISSUE TITLE
Intellij clone下来后无法识别为maven项目

### ISSUE THREAD

**Issue by nl101531** [sdksdk0/taotaoMalls#1]
这种项目不应该把父pom.xml放在最外层的吗?

**Comment by sdksdk0** [comment]
@nl101531 你好，我现在上传的目录是一个工作空间，所以导入的话是需要一个个工程进行导入的，对于taotao-manager这个部分，在manager里面分为pojo、mapper、service、web.这里主要是后台部分。对于分布式的架构来说是分开的。当然你说的把父pom.xml放在最外层也是可以的，那样的话可以一次性的进行导入。我这样分开时为了进一步的解耦和，使整个工程看起来更加清晰，更使用于团队开发！

**Comment by nl101531** [comment]
thks,我去学习下
