### ISSUE TITLE
这里面有数据库吗？

### ISSUE THREAD

**Issue by geekzsp** [sdksdk0/taotaoMalls#2]
你好，不知道 方不方便提供数据库。

**Comment by sdksdk0** [comment]
@geekzsp，你好，我刚才把数据库脚本上传了，在parent这工程里面db文件夹下面,有一个zip压缩包的。如果有什么问题欢迎交流！

**Comment by geekzsp** [comment]
import com.github.pagehelper.PageHelper;
import com.github.pagehelper.PageInfo;

这两个类没有啊 提示找不到。。
